import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { toast } from "sonner";
import { FiArrowLeft, FiSave } from "react-icons/fi";
import { createResource, getErrorMessage, getResource, listResource, updateResource } from "../services/adminApi";
import { LoadingState } from "../components/AdminPrimitives";
import "../styles/HeroBannerEditor.css";

const emptyUsage = { coupon: "", user: "", product: "" };
const idOf = (row) => row?.id ?? row?.pk ?? row?.uuid;
const labelOf = (row, fallback) => row?.email || row?.name || row?.title || row?.code || fallback;
const errorMap = (error) => { const data = error?.response?.data; return data && typeof data === "object" ? Object.fromEntries(Object.entries(data).map(([key, value]) => [key, Array.isArray(value) ? value.join(", ") : String(value)])) : {}; };

export default function CouponUsageEditor() {
    const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id);
    const [values, setValues] = useState(emptyUsage); const [options, setOptions] = useState({ coupons: [], users: [], products: [] });
    const [loading, setLoading] = useState(editing); const [saving, setSaving] = useState(false); const [errors, setErrors] = useState({}); const [requestError, setRequestError] = useState("");
    useEffect(() => { let active = true; Promise.all([listResource("coupons", { page_size: 500 }), listResource("users", { page_size: 500 }), listResource("products", { page_size: 500 })]).then(([coupons, users, products]) => { if (active) setOptions({ coupons: coupons.data?.results || [], users: users.data?.results || [], products: products.data?.results || [] }); }).catch((error) => setRequestError(getErrorMessage(error, "Could not load dropdown options."))); if (!editing) return () => { active = false; }; getResource("coupon-usages", id).then((response) => { const row = response.data || {}; setValues({ coupon: String(idOf(row.coupon) ?? row.coupon ?? ""), user: String(idOf(row.user) ?? row.user ?? ""), product: String(idOf(row.product) ?? row.product ?? "") }); }).catch((error) => setRequestError(getErrorMessage(error, "Could not load coupon usage."))).finally(() => setLoading(false)); return () => { active = false; }; }, [editing, id]);
    const setValue = (name, value) => setValues((current) => ({ ...current, [name]: value }));
    const save = async (mode = "list") => { const next = Object.fromEntries(["coupon", "user", "product"].filter((key) => !values[key]).map((key) => [key, "This field is required."])); if (Object.keys(next).length) { setErrors(next); setRequestError("Please correct the highlighted fields."); return; } setSaving(true); setErrors({}); setRequestError(""); try { const payload = { coupon: values.coupon, user: values.user, product: values.product }; const response = editing ? await updateResource("coupon-usages", id, payload) : await createResource("coupon-usages", payload); const savedId = id || idOf(response.data); toast.success(editing ? "Coupon usage updated" : "Coupon usage created"); if (mode === "another") { setValues(emptyUsage); navigate("/eehook-dashboard/coupon-usages/new", { replace: true }); } else if (mode === "continue") navigate(`/eehook-dashboard/coupon-usages/${savedId}/edit`, { replace: true }); else navigate("/eehook-dashboard/coupon-usages"); } catch (error) { setErrors(errorMap(error)); setRequestError(getErrorMessage(error, "Could not save coupon usage.")); toast.error(getErrorMessage(error, "Could not save coupon usage.")); } finally { setSaving(false); } };
    const selectField = (name, label, items, fallback) => <label className={`hero-editor-field ${errors[name] ? "has-error" : ""}`}><span>{label} <em>*</em></span><select value={values[name]} onChange={(event) => setValue(name, event.target.value)}><option value="">----------</option>{items.map((item) => <option key={idOf(item)} value={idOf(item)}>{labelOf(item, fallback)}</option>)}</select>{errors[name] && <small>{errors[name]}</small>}</label>;
    if (loading) return <div className="admin-page"><LoadingState label="Loading coupon usage..." /></div>;
    return <div className="hero-banner-editor-page"><div className="hero-editor-heading"><div><button type="button" className="hero-back-link" onClick={() => navigate("/eehook-dashboard/coupon-usages")}><FiArrowLeft /> Coupon usages</button><h2>Coupon usages</h2></div><div className="hero-breadcrumb">Home&nbsp; / &nbsp;Myapp&nbsp; / &nbsp;Coupon usages&nbsp; / &nbsp;{editing ? "Edit coupon usage" : "Add coupon usage"}</div></div><div className="hero-editor-layout"><section className="hero-editor-card"><div className="hero-editor-form">{selectField("coupon", "Coupon", options.coupons, "Coupon")}{selectField("user", "User", options.users, "User")}{selectField("product", "Product", options.products, "Product")}</div>{requestError && <p className="hero-editor-error">{requestError}</p>}</section><aside className="hero-editor-actions"><button className="hero-save-button" onClick={() => save("list")} disabled={saving}><FiSave /> Save</button><button className="hero-secondary-button" onClick={() => save("another")} disabled={saving}>Save and add another</button><button className="hero-secondary-button" onClick={() => save("continue")} disabled={saving}>Save and continue editing</button></aside></div></div>;
}
